version: "3.8"
services:
  db:
    container_name: OXDB
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    image: percona:5.7-centos
    networks: 
      open-xchange:
        aliases:
          - oxdb
        ipv4_address: 192.168.100.10
    expose:
      - "3306"
    volumes:
      - "db_data:/var/lib/mysql/"
  app:
    depends_on:
      - db
    container_name: OXAPP
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      OPENEXCHANGE_USER_PASS: ${OPENEXCHANGE_USER_PASS}
      OXADMINMASTER_USER_PASS: ${OXADMINMASTER_USER_PASS}
      OXADMIN_PASS: ${OXADMIN_PASS}
      OX_SERVER_MEMORY: ${OX_SERVER_MEMORY}
    build: ./appsuite
    image: oxappsuite:${APP_TAG}
    networks:
      open-xchange:
        aliases:
          - ox
        ipv4_address: 192.168.100.20
    expose:
      - "8009"
    volumes:
      - "ox_configs:/opt/open-xchange/etc"
  web:
    container_name: OXWEB
    build: ./apache  
    image: oxapache:${WEB_TAG}
    networks:
      open-xchange:
        aliases:
          - web
        ipv4_address: 192.168.100.30
    ports:
      - "8080:80"
networks:
  open-xchange:
    ipam:
      config:
        - subnet: 192.168.100.0/24
volumes:
  db_data:
  ox_configs: